# Generated by Django 4.2.3 on 2023-07-16 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='player_list',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='team_list',
        ),
        migrations.AlterField(
            model_name='game',
            name='team_local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamLocal', to='myapp.inscription'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamVisitor', to='myapp.inscription'),
        ),
        migrations.CreateModel(
            name='TeamInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.inscription')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.inscription')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.player')),
            ],
        ),
        migrations.AddField(
            model_name='inscription',
            name='players',
            field=models.ManyToManyField(through='myapp.PlayerInscription', to='myapp.player'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='teams',
            field=models.ManyToManyField(through='myapp.TeamInscription', to='myapp.team'),
        ),
    ]
