# Generated by Django 4.2.3 on 2023-07-16 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_inscription_player_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminscription',
            name='inscription',
        ),
        migrations.RemoveField(
            model_name='teaminscription',
            name='team',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='players',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='teams',
        ),
        migrations.AddField(
            model_name='inscription',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='myapp.player'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='myapp.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(through='myapp.Inscription', to='myapp.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamLocal', to='myapp.team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamVisitor', to='myapp.team'),
        ),
        migrations.DeleteModel(
            name='PlayerInscription',
        ),
        migrations.DeleteModel(
            name='TeamInscription',
        ),
    ]
