# Generated by Django 4.2.3 on 2023-08-05 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_team_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='group',
        ),
        migrations.AddField(
            model_name='inscription',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='myapp.competition'),
        ),
        migrations.AddField(
            model_name='team',
            name='competition',
            field=models.ManyToManyField(related_name='teams', through='myapp.Inscription', to='myapp.competition'),
        ),
    ]
