# Generated by Django 4.2.3 on 2023-07-16 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_teaminscription_inscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='inscription_list',
        ),
        migrations.AddField(
            model_name='inscription',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.season'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.player'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.team'),
        ),
    ]
