# Generated by Django 4.2.3 on 2023-07-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_group_inscription_list_inscription_season_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='player',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='season',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.AddField(
            model_name='group',
            name='inscriptions',
            field=models.ManyToManyField(to='myapp.inscription'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='players',
            field=models.ManyToManyField(to='myapp.player'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='teams',
            field=models.ManyToManyField(to='myapp.team'),
        ),
    ]
