# Generated by Django 4.2.3 on 2023-08-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_inscription_group_inscription_competition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='number_grups',
        ),
        migrations.AddField(
            model_name='season',
            name='number_grups',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
