# Generated by Django 4.2.3 on 2023-08-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_competition_number_grups_season_number_grups'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teams',
            field=models.ManyToManyField(related_name='groups', to='myapp.team'),
        ),
    ]
