# Generated by Django 4.2.3 on 2023-07-16 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_inscription_player_remove_inscription_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.team'),
        ),
    ]
