# Generated by Django 4.2.3 on 2023-07-17 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_player_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='players',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='teams',
        ),
        migrations.AddField(
            model_name='inscription',
            name='name',
            field=models.CharField(default='Inscription', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='inscription_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='myapp.inscription'),
        ),
    ]
