# Generated by Django 4.2.3 on 2023-07-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_inscription_players_remove_inscription_teams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
