# Generated by Django 4.2.3 on 2023-08-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_group_teams_team_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='number_grups',
            field=models.IntegerField(default=0),
        ),
    ]
