# Generated by Django 4.2.3 on 2023-07-17 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_player_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='inscription_list',
            new_name='inscription',
        ),
    ]
