# Generated by Django 4.2.3 on 2023-07-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_inscription_list_team_inscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='player_list',
            field=models.ManyToManyField(related_name='teams', to='myapp.player'),
        ),
    ]
