# Generated by Django 4.2.3 on 2023-07-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_player_team_team_player_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
