# Generated by Django 4.2.3 on 2023-08-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_stadium_location_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
