# Generated by Django 4.2.3 on 2023-08-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_availability_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='days_available',
            field=models.CharField(choices=[('mon', 'Lunes'), ('tue', 'Martes'), ('wed', 'Miércoles'), ('thu', 'Jueves'), ('fri', 'Viernes'), ('sat', 'Sábado'), ('sun', 'Domingo')], default='mon', max_length=50),
        ),
    ]
