# Generated by Django 4.2.3 on 2023-07-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_game_loser_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='goals_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='goals_scored',
            field=models.IntegerField(default=0),
        ),
    ]
