# Generated by Django 4.2.3 on 2023-07-22 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_team_goals_received_team_goals_scored'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='player_list',
        ),
        migrations.AddField(
            model_name='player',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='myapp.season'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='myapp.team'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('team', 'season')},
        ),
    ]
