# Generated by Django 4.2.3 on 2023-08-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_availability_closing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='competition',
            field=models.ManyToManyField(related_name='locations', to='myapp.competition'),
        ),
    ]
