# Generated by Django 4.2.3 on 2023-07-22 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_team_player_list_player_season_player_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='myapp.season'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to='myapp.team'),
        ),
    ]
