# Generated by Django 4.2.3 on 2023-07-22 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_player_season_alter_player_team'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='PlayerTeamSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.team')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='season',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
    ]
