# Generated by Django 4.2.3 on 2023-08-08 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_location_competition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='competition',
        ),
    ]
