# Generated by Django 4.2.3 on 2023-08-11 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_game_location_game_phase_alter_game_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='myapp.group'),
        ),
    ]
