# Generated by Django 4.2.3 on 2023-07-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_sport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='awards',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='rules_and_regulations',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
