# Generated by Django 4.2.3 on 2023-07-25 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_competition_awards_competition_rules_and_regulations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='sport_list',
            new_name='sport',
        ),
    ]
