# Generated by Django 4.2.3 on 2023-08-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_team_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='groups',
        ),
        migrations.AddField(
            model_name='team',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='teams', to='myapp.group'),
        ),
    ]
