# Generated by Django 4.2.3 on 2023-08-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_team_groups_team_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, default='img/generic-avatar.png', upload_to='player_images/'),
        ),
    ]
