# Generated by Django 4.2.3 on 2023-07-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_sport_list_competition_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='type_sport',
            field=models.CharField(blank=True, choices=[('I', 'Individual'), ('T', 'Team')], default='T', max_length=1),
        ),
    ]
