# Generated by Django 4.2.3 on 2023-08-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_team_groups_team_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='days_available',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('tue', 'Martes'), ('wed', 'Miércoles'), ('thu', 'Jueves'), ('fri', 'Viernes'), ('sat', 'Sábado'), ('sun', 'Domingo')], default='Lunes', max_length=50),
        ),
    ]
