# Generated by Django 4.2.3 on 2023-08-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_availability_days_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='days_available',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], default='Lunes', max_length=50),
        ),
    ]
