# Generated by Django 4.2.3 on 2023-08-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_availability_days_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='date_start',
        ),
        migrations.AddField(
            model_name='season',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='date_start',
            field=models.DateField(null=True),
        ),
    ]
