# Generated by Django 4.2.3 on 2023-07-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_competition_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='rules_and_regulations',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
