# Generated by Django 4.2.3 on 2023-07-29 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_competition_rules_and_regulations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(default='00:00:00')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='myapp.group')),
                ('team_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_matches', to='myapp.team')),
                ('team_visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_matches', to='myapp.team')),
            ],
        ),
        migrations.RemoveField(
            model_name='season',
            name='modality',
        ),
        migrations.AddField(
            model_name='competition',
            name='type_modality',
            field=models.CharField(choices=[('L', 'League'), ('T', 'Tournament'), ('P', 'Playoff'), ('F', 'Friendly'), ('GS', 'Group Stage'), ('O', 'Other')], default='O', help_text='Type of modality', max_length=2),
        ),
        migrations.DeleteModel(
            name='Modality',
        ),
    ]
