# Generated by Django 4.2.3 on 2023-08-11 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_player_image'),
        ('myapp', '0023_remove_competition_date_end_and_more'),
    ]

    operations = [
    ]
