# Generated by Django 4.2.3 on 2023-07-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_match_remove_season_modality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='inscription',
        ),
    ]
