# Generated by Django 4.2.3 on 2023-08-02 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_team_inscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type_modality', models.CharField(choices=[('L', 'League'), ('T', 'Tournament'), ('P', 'Playoff'), ('F', 'Friendly'), ('GS', 'Group Stage'), ('O', 'Other')], default='O', help_text='Type of modality', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='competition',
            name='type_modality',
        ),
        migrations.AddField(
            model_name='team',
            name='inscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='myapp.inscription'),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.AddField(
            model_name='season',
            name='modality',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.modality'),
        ),
    ]
