# Generated by Django 4.2.3 on 2023-08-13 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_game_team_local_goals_game_team_visitor_goals'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSeasonInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='seasons',
            field=models.ManyToManyField(related_name='teams', through='myapp.TeamSeasonInscription', to='myapp.season'),
        ),
    ]
