# Generated by Django 4.2.3 on 2023-08-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_competition_awards_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='inscriptions',
        ),
        migrations.RemoveField(
            model_name='team',
            name='goals_received',
        ),
        migrations.RemoveField(
            model_name='team',
            name='goals_scored',
        ),
        migrations.RemoveField(
            model_name='team',
            name='inscription',
        ),
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Inscription',
        ),
    ]
