# Generated by Django 4.2.3 on 2023-08-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_team_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerteamseason',
            name='season',
        ),
    ]
