# Generated by Django 4.2.3 on 2023-08-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_team_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='competitions', to='myapp.group'),
        ),
    ]
