# Generated by Django 4.2.3 on 2023-08-04 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_competition_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='season',
        ),
        migrations.AddField(
            model_name='season',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='myapp.competition'),
        ),
        migrations.AlterField(
            model_name='group',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='myapp.season'),
        ),
    ]
