# Generated by Django 4.2.3 on 2023-08-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_player_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='phase',
            field=models.CharField(choices=[('GROUP', 'Group'), ('EIGHTH_FINALS', 'Eighth Finals'), ('QUARTER_FINALS', 'Quarter Finals'), ('SEMI_FINALS', 'Semi Finals'), ('FINAL', 'Final')], default='Group', max_length=50),
        ),
    ]
