# Generated by Django 4.2.3 on 2023-08-14 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_game_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sport'),
        ),
    ]
