# Generated by Django 4.2.3 on 2023-08-04 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_competition_groups_remove_competition_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='myapp.season'),
        ),
    ]
