# Generated by Django 4.2.3 on 2023-08-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_remove_team_groups_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='sport',
            field=models.CharField(choices=[('F', 'Football'), ('B', 'Basketball'), ('V', 'Volleyball'), ('H', 'Handball'), ('T', 'Tennis'), ('O', 'Other')], default='F', max_length=1),
        ),
    ]
